- hosts: all
  tasks:

  - name: add github key
    lineinfile: dest=/etc/ssh/ssh_known_hosts line='|1|KWI6LgcTkLS4a3J/jfyOaS6CIKE=|VIpECtP9TDwqZvzNIUSd01ZyKTI= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' owner=root state=present create=True

  - name: determine the installation user
    sudo: False
    set_fact: remote_user="{{ansible_env['USER']}}"

  - name: determine the installation user home
    sudo: False
    set_fact: remote_home="{{ansible_env['HOME']}}"

  - stat: path=/usr/local/maven/bin/mvn  
    register: mvn_installed

  - stat: path=/usr/local/bin/erl
    register: erlang_installed
  
  - stat: path="{{remote_home}}/otp_src.tar.gz"
    register: erlang_downloaded

  - name: install build dependencies
    sudo: True
    action: yum name="{{item}}" enablerepo=epel state=present 
    with_items:
    - java-1.6.0-openjdk.x86_64
    - libffi-devel
    - ncurses-devel
    - gcc
    - ncurses-devel 
    - java-1.6.0-openjdk-devel
    - openssl-devel

  - name: download erlang archive
    sudo: no
    get_url: url=https://packages.erlang-solutions.com/erlang/esl-erlang-src/otp_src_R16B03.tar.gz dest={{remote_home}}/otp_src.tar.gz mode=0440 force=no
    when: not erlang_installed.stat.exists

  - name: checkout maven installer
    sudo: no
    git: repo=git@github.com:binarytemple/centos-maven-install.git dest=maven_install version=0.1
    register: git_result
    when: not mvn_installed.stat.exists

  - name: run maven installer
    sudo: True
    shell: /bin/bash "{{remote_home}}/maven_install/maven-install.sh" 
    when: not mvn_installed.stat.exists

  - action: setup

  - file: path={{remote_home}}/otp_src mode=0755 state=directory owner={{ansible_env['USER']}} group={{ansible_env['USER']}} #selevel=_default serole=_default setype=_default seuser=_default
    sudo: False
    when: not erlang_installed.stat.exists

  - name: extract
    sudo: False
    unarchive: src="{{remote_home}}/otp_src.tar.gz" dest="{{remote_home}}/otp_src/" copy=no creates="{{remote_home}}/otp_src/README.md"
    when: not erlang_installed.stat.exists

  - name: Install custom erlang
    sudo: True
    shell: "cd {{remote_home}}/otp_src/otp_src_R16B03/  && CFLAGS='-DOPENSSL_NO_EC=1' ./configure && make && make install"
    when: not erlang_installed.stat.exists
