- hosts: all
  tasks:

  - name: add github key
    lineinfile: dest=/etc/ssh/ssh_known_hosts line='|1|KWI6LgcTkLS4a3J/jfyOaS6CIKE=|VIpECtP9TDwqZvzNIUSd01ZyKTI= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' owner=root state=present create=True

  - name: determine the installation user
    sudo: False
    set_fact: remote_user="{{ansible_env['USER']}}"

  - name: determine the installation user home
    sudo: False
    set_fact: remote_home="{{ansible_env['HOME']}}"

  - stat: path=/usr/local/maven/bin/mvn  
    register: mvn_installed

  - stat: path=/usr/local/bin/erl
    register: erlang_installed
  
  - stat: path="{{remote_home}}/otp_src.tar.gz"
    register: erlang_downloaded

  - name: install build dependencies
    sudo: True
    action: yum name="{{item}}" enablerepo=epel state=present 
    with_items:
    - java-1.6.0-openjdk.x86_64
    - libffi-devel
    - ncurses-devel
    - gcc
    - ncurses-devel 
    - java-1.6.0-openjdk-devel
    - openssl-devel

  - name: download erlang archive
    sudo: no
    get_url: url=https://packages.erlang-solutions.com/erlang/esl-erlang-src/otp_src_R16B03.tar.gz dest={{remote_home}}/otp_src.tar.gz mode=0440 force=no
    when: not erlang_installed.stat.exists

  - name: checkout maven installer
    sudo: no
    git: repo=git@github.com:binarytemple/centos-maven-install.git dest=maven_install version=0.1
    register: git_result
    when: not mvn_installed.stat.exists

  - name: run maven installer
    sudo: True
    shell: /bin/bash "{{remote_home}}/maven_install/maven-install.sh" 
    when: not mvn_installed.stat.exists

  - action: setup

  - file: path={{remote_home}}/otp_src mode=0755 state=directory owner={{ansible_env['USER']}} group={{ansible_env['USER']}} #selevel=_default serole=_default setype=_default seuser=_default
    sudo: False
    when: not erlang_installed.stat.exists

  - name: extract
    sudo: False
    unarchive: src="{{remote_home}}/otp_src.tar.gz" dest="{{remote_home}}/otp_src/" copy=no creates="{{remote_home}}/otp_src/README.md"
    when: not erlang_installed.stat.exists

  - name: Install custom erlang
    sudo: True
    #shell: "chown -R {{ansible_env['USER']}}:{{ansible_env['USER']}} {{remote_home}}/otp_src && cd {{remote_home}}/otp_src/ && CFLAGS='-DOPENSSL_NO_EC=1' ./configure && make && make install"
    shell: "cd {{remote_home}}/otp_src/otp_src_R16B03/  && CFLAGS='-DOPENSSL_NO_EC=1' ./configure && make && make install"
    when: not erlang_installed.stat.exists

#- hosts: riak_cluster
#  sudo: True
#  tasks:
#  - name: add github key
#    lineinfile: dest=/etc/ssh/ssh_known_hosts line='|1|KWI6LgcTkLS4a3J/jfyOaS6CIKE=|VIpECtP9TDwqZvzNIUSd01ZyKTI= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' owner=root state=present create=True
#
#  - stat: path=/home/vagrant/otp_src_R16B03/otp_src_R16B03/README.md
#    register: erlang_downloaded
#
#  - stat: path=/home/vagrant/riak_ee/dev/dev1/bin/riak
#    register: riak_installed
#
#  - name: checkout riak_ee
#    sudo: no
#    git: repo=git@github.com:basho/riak_ee.git dest=riak_ee version=riak_ee-2.0.4
#    register: git_result
#    when: not riak_installed.stat.exists
#
#  - name: install build dependencies
#    action: apt name="{{item}}" state=installed
#    with_items:
#    - openssl 
#    - libssl0.9.8
#    - openjdk-7-jdk
#    - libpam0g-dev
#    - libffi-dev
#    - maven
#
#  - stat: path=/usr/local/bin/erl
#    register: erlang_installed
#
#  - stat: path=/home/vagrant/otp_src_R16B03/otp_src_R16B03/README.md
#    register: erlang_downloaded
#
#  - name: download erlang archive
#    sudo: True
#    get_url: url=http://www.erlang.org/download/otp_src_R16B03.tar.gz dest=/home/vagrant/otp_src_R16B03.tar.gz mode=0440 force=no
#    when: not erlang_installed.stat.exists
#
#  - file: path=/home/vagrant/otp_src_R16B03 mode=0644 state=directory
#    when: not erlang_installed.stat.exists
#
#  - name: extract
#    sudo: True
#    unarchive: src=/home/vagrant/otp_src_R16B03.tar.gz dest=/home/vagrant/otp_src_R16B03 copy=no creates=/home/vagrant/otp_src_R16B03/otp_src_R16B03/README.md
#    when: not erlang_installed.stat.exists
#
#  - name: Install custom erlang
#    sudo: True
#    shell: "cd /home/vagrant/otp_src_R16B03/otp_src_R16B03/ && ./configure && make && make install"
#    when: not erlang_installed.stat.exists
#
#  - stat: path=/home/vagrant/riak_ee/dev/dev1/bin/riak
#    register: riak_devrel_riak
#
#  - name: build riak devrel 6
#    sudo: no
#    shell: "(cd /home/vagrant/riak_ee/ && rm -rf ./deps && ./rebar get-deps && make devrel DEVNODES=6  ) > /tmp/build-output.log"
#    when: not riak_devrel_riak.stat.exists
#
##  - name: build riak devrel 6 (2.0.4)
##    sudo: no
##    shell: "(cd /home/vagrant/riak_ee.2.0.4/ && rm -rf ./deps && ./rebar get-deps && make devrel DEVNODES=6  ) > /tmp/build-output.2.0.4.log"
##    when: not riak_devrel_riak.stat.exists
#
##  - name: create riak_ee_5_nodes.tgz archive
##    sudo: no 
##    shell: "cd /home/vagrant && tar zcvfp /vagrant/riak_ee_5_nodes.tgz ./riak_ee --exclude=.git --exclude=deps &> /dev/null"
#
#  - name: ulimit for vagrant/nhs user
#    sudo: yes
#    copy: src='../templates/etc_security_limits.d_nhs.conf' dest='/etc/security/limits.d/nhs.conf' mode=644
#
#- hosts: all
#  sudo: True
#  include: ../remove_proxy.yml
