---
- hosts: all
  sudo: yes
  vars:
    # created with:
    # openssl passwd -salt salty -1 toor
    password: '$1$salty$arRoLOPLdNVmuCIIvozz9.'
  tasks:
    - action: user name=vagrant password="{{password}}" 
    #- action: user name=vagrant password="{{password}}" append=no
