---
- hosts: all
  sudo: yes
  tasks:
  
  - name: fetch the basho 2.x repo install script from packagecloud
    get_url: url=https://packagecloud.io/install/repositories/basho/riak/script.rpm dest=/tmp/basho-repo.sh
  
  - name: install the basho 2.x repo
    shell: /bin/bash /tmp/basho-repo.sh
