---
- hosts: all
  sudo: yes
  tasks:
  - name: upgrade all packages
    yum: name="*" state=latest
  - name: install multiple packages
    action: yum name="{{item}}" enablerepo=epel state=present 
    with_items:
    - vim 
    - tcpdump 
    - zsh
    - git
    - tmux
    - python-pycurl
    - s3cmd
    - curl
